# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/Study/FPGA/Project/digit_reco6/digit_reco6.srcs/sources_1/ip/line_shift_ram/line_shift_ram.xci
# IP: The module: 'line_shift_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Study/FPGA/Project/digit_reco6/digit_reco6.srcs/sources_1/ip/line_shift_ram/line_shift_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'line_shift_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: F:/Study/FPGA/Project/digit_reco6/digit_reco6.srcs/sources_1/ip/line_shift_ram/line_shift_ram.xci
# IP: The module: 'line_shift_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Study/FPGA/Project/digit_reco6/digit_reco6.srcs/sources_1/ip/line_shift_ram/line_shift_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'line_shift_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
