# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/Study/FPGA/Project/digit_reco7/digit_reco7.srcs/sources_1/ip/sys_mmcm/sys_mmcm.xci
# IP: The module: 'sys_mmcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Study/FPGA/Project/digit_reco7/digit_reco7.srcs/sources_1/ip/sys_mmcm/sys_mmcm_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_mmcm'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/Study/FPGA/Project/digit_reco7/digit_reco7.srcs/sources_1/ip/sys_mmcm/sys_mmcm.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/Study/FPGA/Project/digit_reco7/digit_reco7.srcs/sources_1/ip/sys_mmcm/sys_mmcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: F:/Study/FPGA/Project/digit_reco7/digit_reco7.srcs/sources_1/ip/sys_mmcm/sys_mmcm.xci
# IP: The module: 'sys_mmcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Study/FPGA/Project/digit_reco7/digit_reco7.srcs/sources_1/ip/sys_mmcm/sys_mmcm_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/Study/FPGA/Project/digit_reco7/digit_reco7.srcs/sources_1/ip/sys_mmcm/sys_mmcm.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/Study/FPGA/Project/digit_reco7/digit_reco7.srcs/sources_1/ip/sys_mmcm/sys_mmcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
