# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache F:/Study/FPGA/Project/car/.Xil/Vivado-6360-DESKTOP-0TSH46O/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tftg256-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/Study/FPGA/Project/car/car.cache/wt [current_project]
set_property parent.project_path F:/Study/FPGA/Project/car/car.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/Study/FPGA/Project/car/car.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files F:/Study/FPGA/Project/digit_reco12/4.coe
read_verilog -library xil_defaultlib {
  F:/Study/FPGA/Project/car/car.srcs/sources_1/new/CAM_RECO.v
  F:/Study/FPGA/Project/car/car.srcs/sources_1/new/Filter_bit.v
  F:/Study/FPGA/Project/car/car.srcs/sources_1/new/VGA_Interface/VGA.v
  F:/Study/FPGA/Project/car/car.srcs/sources_1/new/ajxd.v
  F:/Study/FPGA/Project/car/car.srcs/sources_1/new/binarization1.v
  F:/Study/FPGA/Project/car/car.srcs/sources_1/new/car.v
  F:/Study/FPGA/Project/car/car.srcs/sources_1/new/Camera_Interface/cmos_capture_RGB565.v
  F:/Study/FPGA/Project/car/car.srcs/sources_1/new/digit_reco.v
  F:/Study/FPGA/Project/car/car.srcs/sources_1/new/digital_tube.v
  F:/Study/FPGA/Project/car/car.srcs/sources_1/new/gauss1.v
  F:/Study/FPGA/Project/car/car.srcs/sources_1/new/Camera_Interface/i2c_OV7670_RGB565_config.v
  F:/Study/FPGA/Project/car/car.srcs/sources_1/new/Camera_Interface/i2c_timing_ctrl.v
  F:/Study/FPGA/Project/car/car.srcs/sources_1/new/matrix3x3.v
  F:/Study/FPGA/Project/car/car.srcs/sources_1/new/matrix_generate_3x3.v
  F:/Study/FPGA/Project/car/car.srcs/sources_1/new/mid-value.v
  F:/Study/FPGA/Project/car/car.srcs/sources_1/new/motor.v
  F:/Study/FPGA/Project/car/car.srcs/sources_1/new/rgb2ycbcr.v
  F:/Study/FPGA/Project/car/car.srcs/sources_1/new/sobel_edge_detector.v
  F:/Study/FPGA/Project/car/car.srcs/sources_1/new/square_frame.v
  F:/Study/FPGA/Project/car/car.srcs/sources_1/new/sr04.v
  F:/Study/FPGA/Project/car/car.srcs/sources_1/new/threshold.v
  F:/Study/FPGA/Project/car/car.srcs/sources_1/new/uart_recv.v
  F:/Study/FPGA/Project/car/car.srcs/sources_1/new/uart_send.v
  F:/Study/FPGA/Project/car/car.srcs/sources_1/new/top.v
}
read_ip -quiet F:/Study/FPGA/Project/car/car.srcs/sources_1/ip/binary_buffer/binary_buffer.xci
set_property used_in_implementation false [get_files -all f:/Study/FPGA/Project/car/car.srcs/sources_1/ip/binary_buffer/binary_buffer_ooc.xdc]

read_ip -quiet F:/Study/FPGA/Project/car/car.srcs/sources_1/ip/line_shift_ram/line_shift_ram.xci
set_property used_in_implementation false [get_files -all f:/Study/FPGA/Project/car/car.srcs/sources_1/ip/line_shift_ram/line_shift_ram_ooc.xdc]

read_ip -quiet F:/Study/FPGA/Project/car/car.srcs/sources_1/ip/sys_mmcm/sys_mmcm.xci
set_property used_in_implementation false [get_files -all f:/Study/FPGA/Project/car/car.srcs/sources_1/ip/sys_mmcm/sys_mmcm_board.xdc]
set_property used_in_implementation false [get_files -all f:/Study/FPGA/Project/car/car.srcs/sources_1/ip/sys_mmcm/sys_mmcm.xdc]
set_property used_in_implementation false [get_files -all f:/Study/FPGA/Project/car/car.srcs/sources_1/ip/sys_mmcm/sys_mmcm_ooc.xdc]

read_ip -quiet F:/Study/FPGA/Project/car/car.srcs/sources_1/ip/frame_buffer/frame_buffer.xci
set_property used_in_implementation false [get_files -all f:/Study/FPGA/Project/car/car.srcs/sources_1/ip/frame_buffer/frame_buffer_ooc.xdc]

read_ip -quiet F:/Study/FPGA/Project/car/car.srcs/sources_1/ip/cordic_sqrt/cordic_sqrt.xci

read_ip -quiet F:/Study/FPGA/Project/car/car.srcs/sources_1/ip/edge_buffer/edge_buffer.xci
set_property used_in_implementation false [get_files -all f:/Study/FPGA/Project/car/car.srcs/sources_1/ip/edge_buffer/edge_buffer_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/Study/FPGA/Project/car/car.srcs/constrs_1/new/Ex_Edge_Detection.xdc
set_property used_in_implementation false [get_files F:/Study/FPGA/Project/car/car.srcs/constrs_1/new/Ex_Edge_Detection.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a35tftg256-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
