# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/Study/FPGA/Project/car/car.srcs/sources_1/ip/img_bit/img_bit.xci
# IP: The module: 'img_bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Study/FPGA/Project/car/car.srcs/sources_1/ip/img_bit/img_bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'img_bit'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: F:/Study/FPGA/Project/car/car.srcs/sources_1/ip/img_bit/img_bit.xci
# IP: The module: 'img_bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Study/FPGA/Project/car/car.srcs/sources_1/ip/img_bit/img_bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'img_bit'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
