# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Study/FPGA/Project/digit_reco11/digit_reco11.srcs/sources_1/ip/edge_buffer/edge_buffer.xci
# IP: The module: 'edge_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Study/FPGA/Project/digit_reco11/digit_reco11.srcs/sources_1/ip/edge_buffer/edge_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'edge_buffer'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/Study/FPGA/Project/digit_reco11/digit_reco11.srcs/sources_1/ip/edge_buffer/edge_buffer.xci
# IP: The module: 'edge_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Study/FPGA/Project/digit_reco11/digit_reco11.srcs/sources_1/ip/edge_buffer/edge_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'edge_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
