# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Study/FPGA/Project/digit_reco4/digit_reco4.srcs/sources_1/ip/binary_buffer/binary_buffer.xci
# IP: The module: 'binary_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Study/FPGA/Project/digit_reco4/digit_reco4.srcs/sources_1/ip/binary_buffer/binary_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'binary_buffer'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/Study/FPGA/Project/digit_reco4/digit_reco4.srcs/sources_1/ip/binary_buffer/binary_buffer.xci
# IP: The module: 'binary_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Study/FPGA/Project/digit_reco4/digit_reco4.srcs/sources_1/ip/binary_buffer/binary_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'binary_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
