set_property PACKAGE_PIN D4 [get_ports {clk_sys}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk_sys}]
create_clock -period 20.000 -waveform {0.000 10.000} [get_ports clk_sys]

set_property PACKAGE_PIN T9 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]

## Buttons
set_property PACKAGE_PIN K3 [get_ports {row[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[0]}]
set_property PACKAGE_PIN M6 [get_ports {row[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[1]}]
set_property PACKAGE_PIN P10 [get_ports {row[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[2]}]
set_property PACKAGE_PIN R10 [get_ports {row[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[3]}]

set_property PACKAGE_PIN R12 [get_ports {col[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[0]}]
set_property PACKAGE_PIN T12 [get_ports {col[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[1]}]
set_property PACKAGE_PIN R11 [get_ports {col[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[2]}]
set_property PACKAGE_PIN T10 [get_ports {col[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[3]}]
set_property PULLDOWN true [get_ports {col[3]}]
set_property PULLDOWN true [get_ports {col[2]}]
set_property PULLDOWN true [get_ports {col[1]}]
set_property PULLDOWN true [get_ports {col[0]}]

## ov7670
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets cmos_pclk_IBUF]
set_property PACKAGE_PIN C6 [get_ports cmos_pclk]
set_property IOSTANDARD LVCMOS33 [get_ports cmos_pclk]

set_property PACKAGE_PIN D9 [get_ports cmos_sclk]
set_property IOSTANDARD LVCMOS33 [get_ports cmos_sclk]
set_property PACKAGE_PIN D8 [get_ports cmos_sdat]
set_property IOSTANDARD LVCMOS33 [get_ports cmos_sdat]
set_property PACKAGE_PIN E6 [get_ports cmos_href]
set_property IOSTANDARD LVCMOS33 [get_ports cmos_href]
set_property PACKAGE_PIN C7 [get_ports cmos_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports cmos_vsync]
set_property PACKAGE_PIN D6 [get_ports cmos_xclk]
set_property IOSTANDARD LVCMOS33 [get_ports cmos_xclk]
set_property PACKAGE_PIN A4 [get_ports cmos_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports cmos_rst_n]

set_property PACKAGE_PIN D5 [get_ports {cmos_data[7]}]
set_property PACKAGE_PIN E5 [get_ports {cmos_data[6]}]
set_property PACKAGE_PIN C4 [get_ports {cmos_data[5]}]
set_property PACKAGE_PIN A7 [get_ports {cmos_data[4]}]
set_property PACKAGE_PIN B7 [get_ports {cmos_data[3]}]
set_property PACKAGE_PIN B6 [get_ports {cmos_data[2]}]
set_property PACKAGE_PIN A5 [get_ports {cmos_data[1]}]
set_property PACKAGE_PIN B5 [get_ports {cmos_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[0]}]

set_property PACKAGE_PIN R13 [get_ports vga_hs]
set_property IOSTANDARD LVCMOS33 [get_ports vga_hs]
set_property PACKAGE_PIN T13 [get_ports vga_vs]
set_property IOSTANDARD LVCMOS33 [get_ports vga_vs]

set_property PACKAGE_PIN M15 [get_ports {vga_r[3]}]
set_property PACKAGE_PIN M16 [get_ports {vga_r[2]}]
set_property PACKAGE_PIN F4  [get_ports {vga_r[1]}]
set_property PACKAGE_PIN F5  [get_ports {vga_r[0]}]
set_property PACKAGE_PIN R15 [get_ports {vga_g[3]}]
set_property PACKAGE_PIN P16 [get_ports {vga_g[2]}]
set_property PACKAGE_PIN P15 [get_ports {vga_g[1]}]
set_property PACKAGE_PIN N16 [get_ports {vga_g[0]}]
set_property PACKAGE_PIN T14 [get_ports {vga_b[3]}]
set_property PACKAGE_PIN P14 [get_ports {vga_b[2]}]
set_property PACKAGE_PIN T15 [get_ports {vga_b[1]}]
set_property PACKAGE_PIN R16 [get_ports {vga_b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[0]}]

#7 segment display
set_property PACKAGE_PIN P11 [get_ports {seg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property PACKAGE_PIN N12 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property PACKAGE_PIN L14 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property PACKAGE_PIN K13 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property PACKAGE_PIN K12 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property PACKAGE_PIN P13 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property PACKAGE_PIN M14 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property PACKAGE_PIN L13 [get_ports {seg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[7]}]

set_property PACKAGE_PIN G12 [get_ports {an[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
set_property PACKAGE_PIN H13 [get_ports {an[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
set_property PACKAGE_PIN M12 [get_ports {an[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
set_property PACKAGE_PIN N13 [get_ports {an[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]
set_property PACKAGE_PIN N14 [get_ports {an[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[4]}]
set_property PACKAGE_PIN N11 [get_ports {an[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[5]}]

#sr04
set_property PACKAGE_PIN E13 [get_ports trig]
set_property IOSTANDARD LVCMOS33 [get_ports trig]
set_property PACKAGE_PIN E12 [get_ports echo]
set_property IOSTANDARD LVCMOS33 [get_ports echo]

##UART
set_property PACKAGE_PIN F13 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]
set_property PACKAGE_PIN F12 [get_ports uart_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]

set_property PACKAGE_PIN G14 [get_ports uart1_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart1_rxd]
set_property PACKAGE_PIN F14 [get_ports uart1_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart1_txd]

#pwm
set_property PACKAGE_PIN D13 [get_ports pwm1]
set_property IOSTANDARD LVCMOS33 [get_ports pwm1]
set_property PACKAGE_PIN C13 [get_ports pwm2]
set_property IOSTANDARD LVCMOS33 [get_ports pwm2]
set_property PACKAGE_PIN D11 [get_ports pwm3]
set_property IOSTANDARD LVCMOS33 [get_ports pwm3]
set_property PACKAGE_PIN C11 [get_ports pwm4]
set_property IOSTANDARD LVCMOS33 [get_ports pwm4]
